kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with TrustyAI Explainability Library for explaining
      predictions in a notebook
    opendatahub.io/notebook-image-name: Explainable Data Science
    opendatahub.io/notebook-image-url: 'https://quay.io/tteofili/s2i-trustyai-notebook'
    openshift.io/image.dockerRepositoryCheck: '2023-01-31T08:27:22Z'
  resourceVersion: '131259473'
  name: s2i-explainable-data-science-notebook
  uid: 186dbe11-77e9-4c38-ace2-208a83501d4d
  creationTimestamp: '2023-031-31T09:56:08Z'
  generation: 2
  namespace: odh
  labels:
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: v0.0.1
      annotations:
        opendatahub.io/notebook-python-dependencies: '[{"name":"trustyai","version":"0.2.8"}]'
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.6"}]'
        openshift.io/imported-from: quay.io/tteofili/s2i-trustyai-notebook
      from:
        kind: DockerImage
        name: quay.io/tteofili/s2i-trustyai-notebook
      generation: 10
      importPolicy: {}
      referencePolicy:
        type: Source
